name : continous intergration

on:
  push:
    branches: ["main"]

jobs:
  build:
    run-on: ubuntu-latest

    steps: 
      -name: checkout repository
       uses: action/checkout@v4

      -name: CI Check
       run: echo "contiousn intergration successful"
